routes:
  /: home

collections:
  /insights/:
    permalink: /{year}/{month}/{day}/{slug}/
    template: tag
    filter: tag:hash-insights

  /stories/:
    permalink: /{year}/{month}/{day}/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
